# Generated by Django 4.1.2 on 2022-10-24 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
